# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- qa-testing

pool:
  name: 'TestPool'

steps:
- script: |
    echo Setting JAVA_HOME
    set JAVA_HOME=C:\Program Files\Java\jdk-21
    echo %JAVA_HOME%
  displayName: 'Set JAVA_HOME'

- script: |
    echo Setting MAVEN_HOME
    set MAVEN_HOME=C:\Users\User\Downloads\apache-maven-3.9.9-bin
    set PATH=%MAVEN_HOME%\bin;%PATH%
    echo MAVEN_HOME is set to %MAVEN_HOME%
    echo Updated PATH: %PATH%
    mvn -version
  displayName: 'Print Debugging Information'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'


